# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc595165ca79ed5d8bc150dfec245857"
name = "synchronisation-sumup"
application_url = "https://sumup-shopify-sync.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [ "app/uninstalled", "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_inventory,read_locations"

[auth]
redirect_urls = [ "https://sumup-shopify-sync.onrender.com/api/auth" ]
